name: Auto-merge

on: pull_request_target


jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1.3
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
