name: Auto-merge

on: pull_request_target


jobs:
  auto-merge:
    if: github.actor == 'dependabot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
